apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windows-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: default # Replace with your storage class if needed
