apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: starwinappkey # Placeholder
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
    tenantId: 6a6a4c39-cb56-4522-b88d-872249682c4c
