apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: <KEY_VAULT_NAME> # Placeholder
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
    tenantId: <azure-tenant-id>
